In [4]:
import numpy as np

n = 100_000_000
dice = np.random.randint(1, 7, size=(n, 2))
print(dice)
sums = np.sum(dice, axis=1)
print(sums)
values, counts = np.unique(sums, return_counts=True)
print(values)
print(counts)
prob_d = dict(zip(values, counts/n))
print(prob_d)

a = [1, 2, 3, 4, 5]
b = [1, 2, 3, 4, 5]
list(zip(a, b))

[[1 4]
 [4 6]
 [3 2]
 ...
 [4 2]
 [5 2]
 [6 1]]
[ 5 10  5 ...  6  7  7]
[ 2  3  4  5  6  7  8  9 10 11 12]
[ 2775090  5548810  8334791 11113382 13888644 16669705 13890412 11115081
  8333698  5553464  2776923]
{np.int64(2): np.float64(0.0277509), np.int64(3): np.float64(0.0554881), np.int64(4): np.float64(0.08334791), np.int64(5): np.float64(0.11113382), np.int64(6): np.float64(0.13888644), np.int64(7): np.float64(0.16669705), np.int64(8): np.float64(0.13890412), np.int64(9): np.float64(0.11115081), np.int64(10): np.float64(0.08333698), np.int64(11): np.float64(0.05553464), np.int64(12): np.float64(0.02776923)}


[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]

### Catan

In [11]:
def eval_catan_vertex(prob_d, vertex):
    total_prob = 0
    for number in vertex:
        total_prob += prob_d[number]
    return total_prob
 
options = [
    (2, 3, 4),
    (8, 6, 12),
    (6, 10),
    (3, 6, 4),
]
# opt_dict = {}
# for option in options:
#     opt_dict[option] = float(eval_catan_vertex(prob_d, option).round(2))
opt_dict = {option: float(eval_catan_vertex(prob_d, option).round(2)) for option in options}
print(opt_dict)

{(2, 3, 4): 0.17, (8, 6, 12): 0.31, (6, 10): 0.22, (3, 6, 4): 0.28}


### Backgammon

In [127]:
dice[:, 0]

array([5, 4, 1, 4, 6, 5, 3, 6, 1, 2], dtype=int32)

In [183]:
n = 10_000_000
dice = np.random.randint(1, 7, size=(n, 2))
dice_ndbl = dice[dice[:, 0] != dice[:, 1]]
dice_dbl = dice[dice[:, 0] == dice[:, 1]]
# print("Non-doubles:")
# print(dice_ndbl)
# print("Doubles:")
# print(dice_dbl)

sum_dice_ndbl = np.sum(dice_ndbl, axis=1)
# print(sum_dice_ndbl)
dice_fl_ndbl = dice_ndbl.flatten()
# print(dice_fl_ndbl)

opt_ndbl = np.concat([sum_dice_ndbl, dice_fl_ndbl])
# print("Options for non-doubles:")
# print(opt_ndbl)

dbl_column = dice_dbl[:, 0]
x1 = dbl_column
x2 = np.array([double * 2 for double in dbl_column])
x3 = np.array([double * 3 for double in dbl_column])
x4 = np.array([double * 4 for double in dbl_column])

opt_dbl = np.concatenate([x1, x2, x3, x4])


print("Options for doubles:")
# print(opt_dbl)

opt_total = np.concatenate([opt_ndbl, opt_dbl])
# print("All options:")
# print(opt_total)

unique_options, counts = np.unique(opt_total, return_counts=True)
# print("Unique options:")
# print(unique_options)
# print("Counts:")
# print(counts)

prob_total = dict(zip(unique_options.tolist(), (counts/n).tolist()))
print("Probabilities total:")
print(prob_total)


Options for doubles:
Probabilities total:
{1: 0.3056548, 2: 0.3332673, 3: 0.3887784, 4: 0.4166523, 5: 0.4167205, 6: 0.4721798, 7: 0.1670147, 8: 0.1666403, 9: 0.1388742, 10: 0.083103, 11: 0.0555792, 12: 0.0833371, 15: 0.0277068, 16: 0.0277989, 18: 0.0277753, 20: 0.0277068, 24: 0.0277753}


### Matrix multiplication

matrix multiplication is a binary operation that takes a pair of matrices, and produces another matrix. In order to multiply two matrices, the number of columns in the first matrix must be equal to the number of rows in the second matrix. You can only multiply a matrix of size **(m,n)** with a matrix of size **(n,p)**. The resulting matrix will have the size **(m,p)**.
 
example in latex with (2,3) @ (3,4):
$$
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23}
\end{pmatrix}
\begin{pmatrix}
b_{11} & b_{12} & b_{13} & b_{14} \\
b_{21} & b_{22} & b_{23} & b_{24} \\
b_{31} & b_{32} & b_{33} & b_{34}
\end{pmatrix}
=
\begin{pmatrix}
c_{11} & c_{12} & c_{13} & c_{14} \\
c_{21} & c_{22} & c_{23} & c_{24}
\end{pmatrix}
$$
 
internal calculation:
$$
\begin{pmatrix}
a_{11}b_{11}+a_{12}b_{21}+a_{13}b_{31} & a_{11}b_{12}+a_{12}b_{22}+a_{13}b_{32} & a_{11}b_{13}+a_{12}b_{23}+a_{13}b_{33} & a_{11}b_{14}+a_{12}b_{24}+a_{13}b_{34} \\
a_{21}b_{11}+a_{22}b_{21}+a_{23}b_{31} & a_{21}b_{12}+a_{22}b_{22}+a_{23}b_{32} & a_{21}b_{13}+a_{22}b_{23}+a_{23}b_{33} & a_{21}b_{14}+a_{22}b_{24}+a_{23}b_{34}
\end{pmatrix}
$$