# NumPy Labs


In [18]:
import numpy as np

Create an array of 10 zeros


In [19]:
arr1 = np.zeros(10, dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Create an array of 10 ones

In [20]:
arr1 = np.ones(10, dtype=int)
arr1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Create an array of 10 fives

In [25]:
arr1 = np.full(10, 5, dtype=int)
arr1

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

Create an array of the integers from 10 to 50

In [31]:
arr1 = np.arange(10, 51)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of all the even integers from 10 to 50

In [33]:
arr1 = np.arange(10, 51, 2)
arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [39]:
arr1 = np.arange(0, 9)
arr1 = arr1.reshape(3, 3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix

In [43]:
arr = np.eye(3, dtype=int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Use NumPy to generate a random number between 0 and 1

In [280]:
random_number = np.random.rand()
random_number

0.9945743513273857

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [281]:
arr = np.abs(np.random.randn(25)).astype(int)
arr

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0])

Create the following matrix

Create an array of 20 linearly spaced points between 0 and 1

In [282]:
arr = np.linspace(0, 1, 20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Write a function that takes as input a 2-D ndarray and scales the last row and column by 2

In [339]:
def scale_last_row_and_col_by_2(nparray):
    nparray[-1, :] *= 2
    nparray[:, -1] *= 2
    return nparray

arr = np.random.rand(5, 5)
scaled_arr = scale_last_row_and_col_by_2(arr)
print("Original array:\n", arr)
print("Scaled array:\n", scaled_arr)

Original array:
 [[7.50043381e-01 6.69521224e-01 7.51733735e-01 8.79433027e-01
  9.11065286e-01]
 [9.84234597e-01 1.22949119e-01 8.43047389e-03 4.32049593e-01
  8.05732352e-01]
 [7.87295009e-01 6.27580881e-01 4.18519200e-01 2.81590532e-03
  1.79511178e+00]
 [8.20690865e-01 1.43463182e-01 3.15571858e-01 1.54489519e-01
  1.36612350e+00]
 [1.86451658e+00 7.08238581e-01 3.38808131e-01 6.87671095e-01
  3.94929177e+00]]
Scaled array:
 [[7.50043381e-01 6.69521224e-01 7.51733735e-01 8.79433027e-01
  9.11065286e-01]
 [9.84234597e-01 1.22949119e-01 8.43047389e-03 4.32049593e-01
  8.05732352e-01]
 [7.87295009e-01 6.27580881e-01 4.18519200e-01 2.81590532e-03
  1.79511178e+00]
 [8.20690865e-01 1.43463182e-01 3.15571858e-01 1.54489519e-01
  1.36612350e+00]
 [1.86451658e+00 7.08238581e-01 3.38808131e-01 6.87671095e-01
  3.94929177e+00]]


Create a numpy array with 100 numbers from 1 to 20. You are not allowed to use any loop

In [340]:
arr = np.linspace(1, 20, 100)
arr

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

Create a numpy array containing the sine of the numbers from the above array. 

In [341]:
arr = np.linspace(1, 20, 100)
sine_arr = np.sin(arr)
sine_arr

array([ 0.84147098,  0.92908054,  0.98257421,  0.99998769,  0.98068157,
        0.92536476,  0.8360685 ,  0.71607176,  0.56978082,  0.40256749,
        0.22057186,  0.03047682, -0.16073733, -0.34604919, -0.51865411,
       -0.67221402, -0.8010902 , -0.90055029, -0.96694212, -0.99782778,
       -0.99207314, -0.94988952, -0.8728259 , -0.76371206, -0.62655467,
       -0.46639016, -0.28909977, -0.10119362,  0.09042837,  0.27872982,
        0.45679629,  0.61808918,  0.7566858 ,  0.86749687,  0.9464534 ,
        0.99065611,  0.99848187,  0.96964331,  0.9051994 ,  0.8075165 ,
        0.68018156,  0.52787031,  0.35617562,  0.17140215, -0.01966522,
       -0.21001048, -0.39264414, -0.56085989, -0.70848083, -0.83008631,
       -0.92121097, -0.97850871, -0.99987556, -0.98452691, -0.93302638,
       -0.84726506, -0.73039212, -0.58669914, -0.42146253, -0.24074979,
       -0.05119671,  0.14023632,  0.32651987,  0.50081358,  0.6567174 ,
        0.78850651,  0.89134161,  0.9614466 ,  0.99624721,  0.99

Compute the dot product of arrays [1,2,3,4] and [cos(1),cos(2), cos(3),cos(4)], but first you have to reshape them into  2-dimensional arrays


In [342]:
arr1 = [1,2,3,4]
arr2 = [np.cos(1), np.cos(2), np.cos(3), np.cos(4)]
arr1 = np.array(arr1).reshape(2, 2)
arr2 = np.array(arr2).reshape(2, 2)
result = np.dot(arr1, arr2)
result

array([[-1.43968269, -1.72343408],
       [-2.33906307, -3.86301499]])

Create two numpy arrays (3,3)  - A, B


In [343]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

compute A + B

In [344]:
A + B

array([[0.87283732, 1.66545306, 1.31628391],
       [0.58015619, 1.71966892, 1.27378743],
       [0.87198004, 0.46268032, 1.08630265]])

compute 3A + B

In [345]:
A3 = 3 * A
A3 + B


array([[1.20250251, 3.56554458, 3.11262152],
       [1.57218988, 3.34928737, 2.45870532],
       [2.02383867, 0.7733486 , 1.65422448]])

Find the maximum and the minimum of B

In [346]:
B_max = np.max(B)
B_min = np.min(B)
B_max, B_min

(np.float64(0.9048597006854331), np.float64(0.08413935125592509))

Normalize the matrix B by adding a constant c that makes its minimum be equal to 0

In [347]:
C = np.min(B)
B = B - C
B

array([[0.62386537, 0.63126795, 0.33397576],
       [0.        , 0.82072035, 0.59718913],
       [0.21191138, 0.22320684, 0.71820239]])

Compute the sum of the elements in A

In [348]:
sum_A = np.sum(A)
sum_A

np.float64(4.9315565374407635)

Compute the transpose of A

In [349]:
trans_A = np.transpose(A)
trans_A

array([[0.1648326 , 0.49601684, 0.57592931],
       [0.95004576, 0.81480922, 0.15533414],
       [0.8981688 , 0.59245895, 0.28396091]])

Compute the inverse of A. Use numpy.linalg

In [350]:
A_inv = np.linalg.inv(A)
A_inv

array([[-1.00277731,  0.93739623,  1.2159931 ],
       [-1.44190131,  3.38571758, -2.50325964],
       [ 2.82259038, -3.75330347,  2.42468442]])

Compute the determinant of A

In [351]:
det_A = np.linalg.det(A)
det_A

np.float64(-0.13895894029961142)

Solve the following equations:<br>
    X  + 2Y = 3<br/>
    3X + 4Y = 0

In [352]:
solution = np.linalg.solve(A, B)
solution

array([[-0.36791526,  0.40773696,  1.09822867],
       [-1.4300215 ,  1.30975657, -0.2574934 ],
       [ 2.27473461, -0.75739557,  0.44265887]])