In [3]:
import numpy as np


### Arrays operations

In [ ]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

arr1 = np.array(list1)
arr2 = np.array(list2)

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]


### Array Attributes

In [6]:
def show_array_attributes(arr):
    print("arr:", arr)
    print("arr.dtype:", arr.dtype)
    print("arr.ndim:", arr.ndim)
    print("arr.shape:", arr.shape)
    print("arr.itemsize:", arr.itemsize)
    print("arr.size:", arr.size)
    print("arr.nbytes:", arr.nbytes)    
 
 
arr1 = np.array(list1)
show_array_attributes(arr1)

arr1 = np.array(list1, dtype=np.float32)
show_array_attributes(arr1)

arr = np.array([[1, 2, 3], [4, 5, 6]])
show_array_attributes(arr)

arr: [1 2 3 4 5]
arr.dtype: int64
arr.ndim: 1
arr.shape: (5,)
arr.itemsize: 8
arr.size: 5
arr.nbytes: 40
arr: [1. 2. 3. 4. 5.]
arr.dtype: float32
arr.ndim: 1
arr.shape: (5,)
arr.itemsize: 4
arr.size: 5
arr.nbytes: 20
arr: [[1 2 3]
 [4 5 6]]
arr.dtype: int64
arr.ndim: 2
arr.shape: (2, 3)
arr.itemsize: 8
arr.size: 6
arr.nbytes: 48


In [8]:
arr1 = np.array([
    [1, 2, 3, 4, 5],
])
arr2 = np.array([1, 2, 3, 4, 5])
show_array_attributes(arr1)
show_array_attributes(arr2)

arr: [[1 2 3 4 5]]
arr.dtype: int64
arr.ndim: 2
arr.shape: (1, 5)
arr.itemsize: 8
arr.size: 5
arr.nbytes: 40
arr: [1 2 3 4 5]
arr.dtype: int64
arr.ndim: 1
arr.shape: (5,)
arr.itemsize: 8
arr.size: 5
arr.nbytes: 40


In [9]:
# 2x3 RGB image
arr3 = np.array([
    [
        [255, 0, 0],   # Red
        [0, 255, 0],   # Green
        [0, 0, 255]    # Blue
    ],
    [
        [255, 255, 0], # Yellow
        [0, 255, 255], # Cyan
        [255, 0, 255]  # Magenta
    ]
])

In [10]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("arr1[0]:", arr1[0])
print("arr1[1]:", arr1[1])
print("arr1[-1]:", arr1[-1])
print("arr1[-2]:", arr1[-2])

arr1[0]: 1
arr1[1]: 2
arr1[-1]: 10
arr1[-2]: 9


### Array slicing

In [13]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("arr1[0]:", arr1[0])
print("arr1[1]:", arr1[1])
print("arr1[-1]:", arr1[-1])
print("arr1[-2]:", arr1[-2])
 
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("arr1[0]:", arr1[0])
print("arr1[1]:", arr1[1])
print("arr1[-1]:", arr1[-1])
print("arr1[-2]:", arr1[-2])
 
print("arr1[0:5]:", arr1[0:5])
print("arr1[5:]:", arr1[5:])
print("arr1[:5]:", arr1[:5])
print("arr1[::2]:", arr1[::2])
print("arr1[::-1]:", arr1[::-1])
print("arr1[1:9]:", arr1[1:9])
 

arr1[0]: 1
arr1[1]: 2
arr1[-1]: 10
arr1[-2]: 9
arr1[0]: 1
arr1[1]: 2
arr1[-1]: 10
arr1[-2]: 9
arr1[0:5]: [1 2 3 4 5]
arr1[5:]: [ 6  7  8  9 10]
arr1[:5]: [1 2 3 4 5]
arr1[::2]: [1 3 5 7 9]
arr1[::-1]: [10  9  8  7  6  5  4  3  2  1]
arr1[1:9]: [2 3 4 5 6 7 8 9]


In [14]:
arr2 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])
print("arr2:\n", arr2)
print("arr2[0, 0]:\n", arr2[0, 0])
print("arr2[0, 1]:\n", arr2[0, 1])
print("arr2[1, 0]:\n", arr2[1, 0])
print("arr2[1, 1]:\n", arr2[1, 1])
print("arr2[0, :]:\n", arr2[0, :])
print("arr2[1, :]:\n", arr2[1, :])
print("arr2[:, 0]:\n", arr2[:, 0])
print("arr2[:, 1]:\n", arr2[:, 1])
print("arr2[0:2, 0:2]:\n", arr2[0:2, 0:2])

arr2:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
arr2[0, 0]:
 1
arr2[0, 1]:
 2
arr2[1, 0]:
 6
arr2[1, 1]:
 7
arr2[0, :]:
 [1 2 3 4 5]
arr2[1, :]:
 [ 6  7  8  9 10]
arr2[:, 0]:
 [ 1  6 11]
arr2[:, 1]:
 [ 2  7 12]
arr2[0:2, 0:2]:
 [[1 2]
 [6 7]]


In [32]:
# Ex1:
arr1 = np.array([
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
    [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
])
 
# print the following sub-arrays:
# 1. [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# 2. [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
# 3. [1, 11, 21, 31, 41]
# 4. [2, 12, 22, 32, 42]
# 5. [10, 20, 30, 40, 50]
# 6. [[1, 2, 3, 4, 5], [11, 12, 13, 14, 15], [21, 22, 23, 24, 25]]
# 7. [[6, 7, 8, 9, 10], [16, 17, 18, 19, 20], [26, 27, 28, 29, 30]]
# 8. [[2, 3, 4], [12, 13, 14], [22, 23, 24]]
# 9. [[7, 8, 9], [17, 18, 19], [27, 28, 29]]
# 10 [[1 ,3, 5], [11, 13, 15], [21, 23, 25]]

print(arr1[0, :])
print(arr1[1, :])
print(arr1[:, 0])
print(arr1[:, 1])
print(arr1[:, -1])
print(arr1[0:3,0:5])
print(arr1[0:3,5:])
print(arr1[0:3,1:4])
print(arr1[0:3,6:9])
print(arr1[0:3,0:5:2])

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[ 1 11 21 31 41]
[ 2 12 22 32 42]
[10 20 30 40 50]
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
[[ 6  7  8  9 10]
 [16 17 18 19 20]
 [26 27 28 29 30]]
[[ 2  3  4]
 [12 13 14]
 [22 23 24]]
[[ 7  8  9]
 [17 18 19]
 [27 28 29]]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [33]:
def show_aggregation_functions(arr, fn):
    print(f"{fn.__name__}:", fn(arr))
    print(f"{fn.__name__}(arr, axis=0):", fn(arr, axis=0))
    print(f"{fn.__name__}(arr, axis=1):", fn(arr, axis=1))
 
arr2 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
show_aggregation_functions(arr2, np.sum)
show_aggregation_functions(arr2, np.mean)
show_aggregation_functions(arr2, np.min)
show_aggregation_functions(arr2, np.max)
show_aggregation_functions(arr2, np.std)
show_aggregation_functions(arr2, np.var)
show_aggregation_functions(arr2, np.median)
show_aggregation_functions(arr2, np.prod)
show_aggregation_functions(arr2, np.cumsum)
show_aggregation_functions(arr2, np.cumprod)
show_aggregation_functions(arr2, np.argmin)
show_aggregation_functions(arr2, np.argmax)

sum: 55
sum(arr, axis=0): [ 7  9 11 13 15]
sum(arr, axis=1): [15 40]
mean: 5.5
mean(arr, axis=0): [3.5 4.5 5.5 6.5 7.5]
mean(arr, axis=1): [3. 8.]
min: 1
min(arr, axis=0): [1 2 3 4 5]
min(arr, axis=1): [1 6]
max: 10
max(arr, axis=0): [ 6  7  8  9 10]
max(arr, axis=1): [ 5 10]
std: 2.8722813232690143
std(arr, axis=0): [2.5 2.5 2.5 2.5 2.5]
std(arr, axis=1): [1.41421356 1.41421356]
var: 8.25
var(arr, axis=0): [6.25 6.25 6.25 6.25 6.25]
var(arr, axis=1): [2. 2.]
median: 5.5
median(arr, axis=0): [3.5 4.5 5.5 6.5 7.5]
median(arr, axis=1): [3. 8.]
prod: 3628800
prod(arr, axis=0): [ 6 14 24 36 50]
prod(arr, axis=1): [  120 30240]
cumsum: [ 1  3  6 10 15 21 28 36 45 55]
cumsum(arr, axis=0): [[ 1  2  3  4  5]
 [ 7  9 11 13 15]]
cumsum(arr, axis=1): [[ 1  3  6 10 15]
 [ 6 13 21 30 40]]
cumprod: [      1       2       6      24     120     720    5040   40320  362880
 3628800]
cumprod(arr, axis=0): [[ 1  2  3  4  5]
 [ 6 14 24 36 50]]
cumprod(arr, axis=1): [[    1     2     6    24   120]
 [    6

### Algoritmic Functions

In [34]:
arr = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print("arr:", arr)
print("np.sin(arr):", np.sin(arr))
print("np.cos(arr):", np.cos(arr))
print("np.tan(arr):", np.tan(arr))
print("np.arcsin(arr):", np.arcsin(arr))
print("np.arccos(arr):", np.arccos(arr))
print("np.arctan(arr):", np.arctan(arr))
print("np.degrees(arr):", np.degrees(arr))
 

arr: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
np.sin(arr): [0.         0.5        0.70710678 0.8660254  1.        ]
np.cos(arr): [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
np.tan(arr): [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
np.arcsin(arr): [0.         0.55106958 0.90333911        nan        nan]
np.arccos(arr): [1.57079633 1.01972674 0.66745722        nan        nan]
np.arctan(arr): [0.         0.48234791 0.66577375 0.80844879 1.00388482]
np.degrees(arr): [ 0. 30. 45. 60. 90.]


C:\Users\Omerg\AppData\Local\Temp\ipykernel_2956\1212570427.py:6: RuntimeWarning: invalid value encountered in arcsin
  print("np.arcsin(arr):", np.arcsin(arr))
C:\Users\Omerg\AppData\Local\Temp\ipykernel_2956\1212570427.py:7: RuntimeWarning: invalid value encountered in arccos
  print("np.arccos(arr):", np.arccos(arr))


### Filtering

In [35]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 11])
arr2 = np.array([0, 3, 2, 4, 5, 7, 6, 8, 9, 10])
 
print("arr1 == arr2:", arr1 == arr2)
print("arr1[arr1 == arr2]:", arr1[arr1 == arr2])
print("arr1 > arr2:", arr1 > arr2)
print("arr1[arr1 > arr2]:", arr1[arr1 > arr2])
print("(arr1 == arr2) & (arr1 % 2 == 0):", (arr1 == arr2) & (arr1 % 2 == 0))
print("arr1[(arr1 == arr2) & (arr1 % 2 == 0)]:", arr1[(arr1 == arr2) & (arr1 % 2 == 0)])
print("(arr1 > arr2) | (arr1 < arr2):", (arr1 > arr2) | (arr1 < arr2))
print("arr1[(arr1 > arr2) | (arr1 < arr2)]:", arr1[(arr1 > arr2) | (arr1 < arr2)])

arr1 == arr2: [False False False  True  True False False  True  True False]
arr1[arr1 == arr2]: [4 5 8 9]
arr1 > arr2: [ True False  True False False False  True False False  True]
arr1[arr1 > arr2]: [ 1  3  7 11]
(arr1 == arr2) & (arr1 % 2 == 0): [False False False  True False False False  True False False]
arr1[(arr1 == arr2) & (arr1 % 2 == 0)]: [4 8]
(arr1 > arr2) | (arr1 < arr2): [ True  True  True False False  True  True False False  True]
arr1[(arr1 > arr2) | (arr1 < arr2)]: [ 1  2  3  6  7 11]


### Filtering excercise

In [45]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr2 = np.array([0, 3, 2, 4, 5, 7, 6, 8, 8, 11])
 
arr3 = np.array([
    [1, 2, 3, 4, 5],
    [1, 1, 2, 4, 1]
])
# EX2: use filtering:
# 1. print all elements in arr1 that are greater than 5
print(arr1[(arr1 > 5)])
# 2. print all elements in arr2 that are less than 5
print(arr2[(arr2 < 5)])
# 3. print all elements in arr1 that are equal to the corresponding elements in arr2
print(arr1[arr1 == arr2])
# 4. print all elements in arr1 that are greater than the corresponding elements in arr2
print(arr1[arr1 > arr2])
# 5. print all elements in arr1 that are less than the corresponding elements in arr2
print(arr1[arr1 < arr2])
# 6. print all elements in arr1 that are even and equal to the corresponding elements in arr2
print(arr1[(arr1 % 2 == 0) & (arr1 == arr2)])
# 7. print all elements in first line that are equal to the second line in arr3
print(arr3[0][arr3[0] == arr3[1]])

[ 6  7  8  9 10]
[0 3 2 4]
[4 5 8]
[1 3 7 9]
[ 2  6 10]
[4 8]
[1 4]


### Array creation methods (Generation of Arrays)

In [ ]:
# arange method:
print("np.arange(10):", np.arange(10))
print("np.arange(1, 10):", np.arange(1, 10))
print("np.arange(1, 10, 2):", np.arange(1, 10, 2))
print("np.arange(10, 1, -1):", np.arange(10, 1, -1))
print("np.arange(0, 1, 0.1):", np.arange(0, 1, 0.1))

np.arange(10): [0 1 2 3 4 5 6 7 8 9]
np.arange(1, 10): [1 2 3 4 5 6 7 8 9]
np.arange(1, 10, 2): [1 3 5 7 9]
np.arange(10, 1, -1): [10  9  8  7  6  5  4  3  2]
np.arange(0, 1, 0.1): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [48]:
# linspace method:
print("np.linspace(0, 1, 5):", np.linspace(0, 1, 5))
print("np.linspace(0, 1, 10):", np.linspace(0, 1, 10))

np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
np.linspace(0, 1, 10): [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [49]:
#logspace method:
pows = np.linspace(0, 1, 5)
print("pows:", pows)
print("10 ** pows:", 10 ** pows)
print("np.logspace(0, 1, 5):", np.logspace(0, 1, 5))
print("np.logspace(0, 3, 7):", np.logspace(0, 3, 7))
print("np.logspace(0, 9, 10, base=2):", np.logspace(0, 9, 10, base=2))
 

pows: [0.   0.25 0.5  0.75 1.  ]
10 ** pows: [ 1.          1.77827941  3.16227766  5.62341325 10.        ]
np.logspace(0, 1, 5): [ 1.          1.77827941  3.16227766  5.62341325 10.        ]
np.logspace(0, 3, 7): [   1.            3.16227766   10.           31.6227766   100.
  316.22776602 1000.        ]
np.logspace(0, 9, 10, base=2): [  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


### Random numbers

In [50]:
print("np.random.rand():", np.random.rand()) # one random number from uniform distribution [0, 1)
print("np.random.rand(3):", np.random.rand(3)) # array of 3 random numbers from uniform distribution [0, 1)
print("np.random.rand(2, 3):", np.random.rand(2, 3)) # 2x3 array of random numbers from uniform distribution [0, 1

np.random.rand(): 0.09601664737332272
np.random.rand(3): [0.04716705 0.45099247 0.74981224]
np.random.rand(2, 3): [[0.74297105 0.20707999 0.81711793]
 [0.06118369 0.01330595 0.08691121]]


In [51]:
print("np.random.randn():", np.random.randn()) # one random number from standard normal distribution
print("np.random.randn(3):", np.random.randn(3)) # array of 3 random numbers from standard normal distribution
print("np.random.randn(2, 3):", np.random.randn(2, 3)) # 2x3 array of random numbers from standard normal distribution

np.random.randn(): -0.7658323952950516
np.random.randn(3): [ 0.34053817  1.0200644  -0.1944047 ]
np.random.randn(2, 3): [[-1.40031428  1.2660579  -2.03734796]
 [ 0.50847083  0.14374737 -0.60621316]]


In [52]:
nums = np.random.randn(10000)
np.std(nums), np.mean(nums), np.min(nums), np.max(nums)

(np.float64(1.0081650535373488),
 np.float64(-0.005514216154478201),
 np.float64(-4.017761936137314),
 np.float64(4.074345783907063))

In [53]:
nums = np.random.randn(1_000)
np.std(nums), np.mean(nums), np.min(nums), np.max(nums)
 

(np.float64(1.0132934813608607),
 np.float64(0.009003572839136055),
 np.float64(-3.2096505268067044),
 np.float64(2.8981329947366663))

In [85]:
print(np.random.randint(1, 7, (5, 2)))

[[1 1]
 [3 6]
 [2 2]
 [6 3]
 [3 4]]
